fix(shell): format shell files
Signed-off-by: sam bacha <sam@manifoldfinance.com>

diff --git a/src/dapp/libexec/dapp/dapp b/src/dapp/libexec/dapp/dapp
--- a/src/dapp/libexec/dapp/dapp
+++ b/src/dapp/libexec/dapp/dapp
@@ -50,7 +50,6 @@
 ### load=name          start from a previously saved snapshot
 ### dir=directory      testnet directory
 
-
 OPTS="dapp [<options>] <command> [<args>]
 dapp <command> --help
 --
@@ -102,11 +101,11 @@ dir=directory      testnet directory
 set -e
 
 if ! [[ $DAPP_INIT ]]; then
-  export DAPP_INIT=1
-  # shellcheck source=/dev/null
-  [[ -e ~/.dapprc ]] && . ~/.dapprc
-  # shellcheck source=/dev/null
-  [[ $(pwd) != ~ && -e .dapprc ]] && . .dapprc
+	export DAPP_INIT=1
+	# shellcheck source=/dev/null
+	[[ -e ~/.dapprc ]] && . ~/.dapprc
+	# shellcheck source=/dev/null
+	[[ $(pwd) != ~ && -e .dapprc ]] && . .dapprc
 fi
 
 export DAPP_SRC=${DAPP_SRC-src}
@@ -117,78 +116,148 @@ export DAPP_ROOT=${DAPP_ROOT-.}
 export DAPP_REMAPPINGS=${DAPP_REMAPPINGS-"$(dapp-remappings)"}
 
 if [[ $2 = --help ]]; then
-  exec "${0##*/}" help -- "$1"
+	exec "${0##*/}" help -- "$1"
 elif [[ $DAPP_SOLC_VERSION ]]; then
-  v=$DAPP_SOLC_VERSION
-  unset DAPP_SOLC_VERSION
-  exec "${0##*/}---use" "solc:$v" "${@:1}"
+	v=$DAPP_SOLC_VERSION
+	unset DAPP_SOLC_VERSION
+	exec "${0##*/}---use" "solc:$v" "${@:1}"
 elif [[ $1 = -* ]] && command -v "${0##*/}-$1" &>/dev/null; then
-  exec "${0##*/}-$1" "${@:2}"
+	exec "${0##*/}-$1" "${@:2}"
 fi
 
-fail () {
-  echo >&2 "error: $1" && echo >&2
-  exit 1
+fail() {
+	echo >&2 "error: $1" && echo >&2
+	exit 1
 }
 
 eval "$(git rev-parse --parseopt -- "$@" <<<"$OPTS" || echo exit $?)"
 
 shopt -s extglob
 
-
 while [[ $1 ]]; do
-  case $1 in
-    --)                shift; break;;
-    --extract)                export DAPP_BUILD_EXTRACT=1;;
-    --optimize)               export DAPP_BUILD_OPTIMIZE=1;;
-    --legacy)                 export DAPP_BUILD_LEGACY=1;;
+	case $1 in
+	--)
+		shift
+		break
+		;;
+	--extract) export DAPP_BUILD_EXTRACT=1 ;;
+	--optimize) export DAPP_BUILD_OPTIMIZE=1 ;;
+	--legacy) export DAPP_BUILD_LEGACY=1 ;;
 
-    -m|--match)        shift; export DAPP_TEST_MATCH=$1;;
-    -v|--verbose)             export DAPP_TEST_VERBOSITY=1;;
-    --cov-match)       shift; export DAPP_TEST_COV_MATCH=$1;;
-    --verbosity)       shift; export DAPP_TEST_VERBOSITY=$1;;
-    --fuzz-runs)       shift; export DAPP_TEST_FUZZ_RUNS=$1;;
-    --depth)           shift; export DAPP_TEST_DEPTH=$1;;
+	-m | --match)
+		shift
+		export DAPP_TEST_MATCH=$1
+		;;
+	-v | --verbose) export DAPP_TEST_VERBOSITY=1 ;;
+	--cov-match)
+		shift
+		export DAPP_TEST_COV_MATCH=$1
+		;;
+	--verbosity)
+		shift
+		export DAPP_TEST_VERBOSITY=$1
+		;;
+	--fuzz-runs)
+		shift
+		export DAPP_TEST_FUZZ_RUNS=$1
+		;;
+	--depth)
+		shift
+		export DAPP_TEST_DEPTH=$1
+		;;
 
-    --smttimeout)      shift; export DAPP_TEST_SMTTIMEOUT=$1;;
-    --solver)          shift; export DAPP_TEST_SOLVER=$1;;
-    --max-iterations)  shift; export DAPP_TEST_MAX_ITERATIONS=$1;;
-    --smtdebug)               export DAPP_TEST_SMTDEBUG=1;;
-    --coverage)               export DAPP_TEST_COVERAGE=1;;
+	--smttimeout)
+		shift
+		export DAPP_TEST_SMTTIMEOUT=$1
+		;;
+	--solver)
+		shift
+		export DAPP_TEST_SOLVER=$1
+		;;
+	--max-iterations)
+		shift
+		export DAPP_TEST_MAX_ITERATIONS=$1
+		;;
+	--smtdebug) export DAPP_TEST_SMTDEBUG=1 ;;
+	--coverage) export DAPP_TEST_COVERAGE=1 ;;
 
-    --replay)          shift; export DAPP_TEST_REPLAY=$1;;
-    --cache)           shift; export DAPP_TEST_CACHE=$1;;
-    --ffi)                    export DAPP_TEST_FFI=1;;
-    --rpc-url)         shift; export HEVM_RPC=yes; export ETH_RPC_URL=$1;;
-    --rpc-block)       shift; export HEVM_RPC=yes; export DAPP_TEST_NUMBER=$1;;
-    --rpc)             [ -n "$ETH_RPC_URL" ] || fail "ETH_RPC_URL not set.";
-       export HEVM_RPC=yes;;
+	--replay)
+		shift
+		export DAPP_TEST_REPLAY=$1
+		;;
+	--cache)
+		shift
+		export DAPP_TEST_CACHE=$1
+		;;
+	--ffi) export DAPP_TEST_FFI=1 ;;
+	--rpc-url)
+		shift
+		export HEVM_RPC=yes
+		export ETH_RPC_URL=$1
+		;;
+	--rpc-block)
+		shift
+		export HEVM_RPC=yes
+		export DAPP_TEST_NUMBER=$1
+		;;
+	--rpc)
+		[ -n "$ETH_RPC_URL" ] || fail "ETH_RPC_URL not set."
+		export HEVM_RPC=yes
+		;;
 
-    --verify)                 export DAPP_VERIFY_CONTRACT=yes;;
+	--verify) export DAPP_VERIFY_CONTRACT=yes ;;
 
-    --async)                  export DAPP_ASYNC=yes;;
+	--async) export DAPP_ASYNC=yes ;;
 
-    --rpc-port)        shift; export DAPP_TESTNET_RPC_PORT=$1;;
-    --rpc-addr)        shift; export DAPP_TESTNET_RPC_ADDRESS=$1;;
-    --chain-id)        shift; export DAPP_TESTNET_CHAINID=$1;;
-    --period)          shift; export DAPP_TESTNET_PERIOD=$1;;
-    --accounts)        shift; export DAPP_TESTNET_ACCOUNTS=$(($1 - 1));;
-    --save)            shift; export DAPP_TESTNET_SAVE=$1;;
-    --load)            shift; export DAPP_TESTNET_LOAD=$1;;
-    --dir)             shift; export DAPP_TESTNET_gethdir=$1;;
+	--rpc-port)
+		shift
+		export DAPP_TESTNET_RPC_PORT=$1
+		;;
+	--rpc-addr)
+		shift
+		export DAPP_TESTNET_RPC_ADDRESS=$1
+		;;
+	--chain-id)
+		shift
+		export DAPP_TESTNET_CHAINID=$1
+		;;
+	--period)
+		shift
+		export DAPP_TESTNET_PERIOD=$1
+		;;
+	--accounts)
+		shift
+		export DAPP_TESTNET_ACCOUNTS=$(($1 - 1))
+		;;
+	--save)
+		shift
+		export DAPP_TESTNET_SAVE=$1
+		;;
+	--load)
+		shift
+		export DAPP_TESTNET_LOAD=$1
+		;;
+	--dir)
+		shift
+		export DAPP_TESTNET_gethdir=$1
+		;;
 
-
-    *) printf "${0##*/}: internal error: %q\\n" "$1"; exit 1
-  esac; shift
+	\
+		*)
+		printf "${0##*/}: internal error: %q\\n" "$1"
+		exit 1
+		;;
+	esac
+	shift
 done
 
 if ! [ -x "$(command -v "${0##*/}-${1-help}")" ]; then
-    # look for approximate matches
-    echo >&2 "'$1' is not a dapp command. See 'dapp help'."
-    echo >&2
-    echo >&2 "Most similar commands:"
-    find "${0%dapp}" -execdir echo {} ';' | agrep -1 "${0##*/}-${1-help}" >&2
-    exit 1
+	# look for approximate matches
+	echo >&2 "'$1' is not a dapp command. See 'dapp help'."
+	echo >&2
+	echo >&2 "Most similar commands:"
+	find "${0%dapp}" -execdir echo {} ';' | agrep -1 "${0##*/}-${1-help}" >&2
+	exit 1
 fi
 
 "${0##*/}-${1-help}" "${@:2}"
diff --git a/src/dapp/libexec/dapp/dapp-test-geth-experimental b/src/dapp/libexec/dapp/dapp-test-geth-experimental
--- a/src/dapp/libexec/dapp/dapp-test-geth-experimental
+++ b/src/dapp/libexec/dapp/dapp-test-geth-experimental
@@ -18,12 +18,12 @@ shopt -s nullglob
 testnets=("$HOME"/.dapp/testnet/*)
 
 if [[ ${#testnets[@]} -gt 1 ]]; then
-  echo >&2 "dapp-test-geth: Several dapp testnets running: ${testnets[*]}"
-  echo >&2 "dapp-test-geth: I can only handle one, sorry."
-  exit 1
+	echo >&2 "dapp-test-geth: Several dapp testnets running: ${testnets[*]}"
+	echo >&2 "dapp-test-geth: I can only handle one, sorry."
+	exit 1
 elif [[ ${#testnets[@]} -eq 0 ]]; then
-  echo >&2 "dapp-test-geth: Please run 'dapp testnet' in another terminal."
-  exit 1
+	echo >&2 "dapp-test-geth: Please run 'dapp testnet' in another terminal."
+	exit 1
 fi
 
 testnet=${testnets[0]}
@@ -42,26 +42,26 @@ trap clean EXIT
 
 # Go through all the contract ABIs and look for ds-test suites.
 for x in "$DAPP_OUT"/*.abi; do
-  contract=$(sed <<<"$(basename "$x")" s/\.abi$//)
+	contract=$(sed <<<"$(basename "$x")" s/\.abi$//)
 
-  # Deploy one instance per test method.
-  shutup=0
-  while read -r method; do
-    if [[ $shutup -eq 0 ]]; then
-      echo >&2 "dapp-test-geth: deploying test copies for $contract"
-      mkdir "$tmp/$contract"
-      shutup=1
-    fi
-    {
-      SETH_STATUS=1 dapp create "$contract" >"$tmp/$contract/$method" 2>/dev/null
-      if [[ ! $? ]]; then touch "$tmp/fail"; fi
-    } &
-  done < <(dapp --find-test-methods "$x" 2>/dev/null)
+	# Deploy one instance per test method.
+	shutup=0
+	while read -r method; do
+		if [[ $shutup -eq 0 ]]; then
+			echo >&2 "dapp-test-geth: deploying test copies for $contract"
+			mkdir "$tmp/$contract"
+			shutup=1
+		fi
+		{
+			SETH_STATUS=1 dapp create "$contract" >"$tmp/$contract/$method" 2>/dev/null
+			if [[ ! $? ]]; then touch "$tmp/fail"; fi
+		} &
+	done < <(dapp --find-test-methods "$x" 2>/dev/null)
 done
 
 wait
 if [ -e "$tmp/fail" ]; then
-  echo >&2 "dapp-test-geth: error: some contract creations failed"
+	echo >&2 "dapp-test-geth: error: some contract creations failed"
 fi
 
 mkdir "$tmp/results"
@@ -70,7 +70,7 @@ no0x() { echo "${1#0x}"; }
 setUp=$(no0x "$(seth calldata "setUp()")")
 assemble() { tr -d '\n '; }
 mkruntime() {
-  assemble <<.
+	assemble <<.
   60 00
   60 00
   60 20
@@ -118,12 +118,12 @@ mkruntime() {
 }
 
 mkcreation() {
-  address=$(no0x "$1")
-  method=$(no0x "$(seth calldata "$2()")")
-  runtime=$(mkruntime "$address" "$method")
-  codesize=${#runtime}
-  codesize=$((codesize / 2))
-  assemble <<.
+	address=$(no0x "$1")
+	method=$(no0x "$(seth calldata "$2()")")
+	runtime=$(mkruntime "$address" "$method")
+	codesize=${#runtime}
+	codesize=$((codesize / 2))
+	assemble <<.
   61 $(printf "%04x" "$codesize")
   60 00
   81
@@ -135,37 +135,40 @@ mkcreation() {
 .
 }
 
-fail() { echo "FAIL $contract::$method"; touch "$tmp/fail"; }
+fail() {
+	echo "FAIL $contract::$method"
+	touch "$tmp/fail"
+}
 pass() { echo "PASS $contract::$method"; }
 
 testcase() {
-  creation=$(mkcreation "$address" "$method")
-  testaddress=$(seth send --create "$creation" --status 2>/dev/null)
-  if seth send "$testaddress" --status 2>/dev/null; then
-    result=$(seth call "$address" 'failed()(bool)')
-    if [[ "$result" == true ]]; then
-      if [[ "$method" == testFail* ]]; then pass; else fail; fi
-    else
-      if [[ "$method" == testFail* ]]; then fail; else pass; fi
-    fi
-  else
-    if [[ "$method" == testFail* ]]; then pass; else fail; fi
-  fi
+	creation=$(mkcreation "$address" "$method")
+	testaddress=$(seth send --create "$creation" --status 2>/dev/null)
+	if seth send "$testaddress" --status 2>/dev/null; then
+		result=$(seth call "$address" 'failed()(bool)')
+		if [[ "$result" == true ]]; then
+			if [[ "$method" == testFail* ]]; then pass; else fail; fi
+		else
+			if [[ "$method" == testFail* ]]; then fail; else pass; fi
+		fi
+	else
+		if [[ "$method" == testFail* ]]; then pass; else fail; fi
+	fi
 }
 
 # Run all test cases in parallel...
 for contract in "$tmp"/*; do
-  for method in $(printf "%s\\n" "$contract"/*); do
-    address=$(cat "$method")
-    contract=$(basename "$contract")
-    method=$(basename "$method")
-    testcase &
-  done
+	for method in $(printf "%s\\n" "$contract"/*); do
+		address=$(cat "$method")
+		contract=$(basename "$contract")
+		method=$(basename "$method")
+		testcase &
+	done
 done
 
 wait
 
 if [ -e "$tmp/fail" ]; then
-  echo >&2 "dapp-test-geth: some unit tests failed"
-  exit 1
+	echo >&2 "dapp-test-geth: some unit tests failed"
+	exit 1
 fi
diff --git a/src/hevm/run-consensus-tests b/src/hevm/run-consensus-tests
--- a/src/hevm/run-consensus-tests
+++ b/src/hevm/run-consensus-tests
@@ -7,8 +7,8 @@ set -e
 HEVM=${HEVM:-hevm}
 
 if [[ "$#" -lt 1 ]]; then
-  echo >&2 "usage: $(basename "$0") <tests-dir>"
-  exit 1
+	echo >&2 "usage: $(basename "$0") <tests-dir>"
+	exit 1
 fi
 
 tests=$1
@@ -18,7 +18,7 @@ skip=$4
 timeout=${5:-10}
 
 _html() {
-cat <<.
+	cat <<.
 <!doctype html>
 <title>hevm test results</title>
 <style>
@@ -65,46 +65,47 @@ $(echo $passed)
 }
 
 {
-  cd "$tests"
-  for x in VMTests/*/*; do
-    if [[ $x =~ .*$match.* ]] && [[ -n $skip && $x =~ .*$skip.* ]]; then
-      for job in $(<$x jq '.|keys[]' -r); do
-        echo "$x $job skip"
-      done
-    elif [[ $x =~ .*$match.* ]]; then
-      echo -n "$x " ; "$HEVM" vm-test --file $x --timeout $timeout 2>&1
-    fi
-  done
+	cd "$tests"
+	for x in VMTests/*/*; do
+		if [[ $x =~ .*$match.* ]] && [[ -n $skip && $x =~ .*$skip.* ]]; then
+			for job in $(jq <$x '.|keys[]' -r); do
+				echo "$x $job skip"
+			done
+		elif [[ $x =~ .*$match.* ]]; then
+			echo -n "$x "
+			"$HEVM" vm-test --file $x --timeout $timeout 2>&1
+		fi
+	done
 } | {
-  while read path test outcome; do
-    echo >&2 "$path $test $outcome"
-    category=$(dirname "$path")
-    testcase=$(basename "${path%.json}")
-    row="<tr><td class=testcase>$testcase<td>$outcome<td class=category>$category"
-    row+=$'\n'
-    case $outcome in
-      ok)      passed+=$row ;;
-      skip)    skipped+=$row ;;
-      timeout) timouts+=row ;;
-      *)       failed+=$row ;;
-    esac
-  done
+	while read path test outcome; do
+		echo >&2 "$path $test $outcome"
+		category=$(dirname "$path")
+		testcase=$(basename "${path%.json}")
+		row="<tr><td class=testcase>$testcase<td>$outcome<td class=category>$category"
+		row+=$'\n'
+		case $outcome in
+		ok) passed+=$row ;;
+		skip) skipped+=$row ;;
+		timeout) timouts+=row ;;
+		*) failed+=$row ;;
+		esac
+	done
 
-  sum () { echo -ne "$1" | wc -l | awk '{print $1}'; }
+	sum() { echo -ne "$1" | wc -l | awk '{print $1}'; }
 
-  nfail=$(sum "$failed")
-  npass=$(sum "$passed")
-  nskip=$(sum "$skipped")
-  ntime=$(sum "$timeouts")
+	nfail=$(sum "$failed")
+	npass=$(sum "$passed")
+	nskip=$(sum "$skipped")
+	ntime=$(sum "$timeouts")
 
-  echo >&2 "passed: $npass"
-  echo >&2 "failed: $nfail"
-  echo >&2 "timeout: $ntime"
-  echo >&2 "skipped: $nskip"
+	echo >&2 "passed: $npass"
+	echo >&2 "failed: $nfail"
+	echo >&2 "timeout: $ntime"
+	echo >&2 "skipped: $nskip"
 
-  if [[ $html == "True" ]]; then
-    _html
-  fi
+	if [[ $html == "True" ]]; then
+		_html
+	fi
 
-  [[ $nfail -gt 0 ]] && exit 1 || exit 0
+	[[ $nfail -gt 0 ]] && exit 1 || exit 0
 }
diff --git a/src/seth/libexec/seth/seth---nix-run b/src/seth/libexec/seth/seth---nix-run
--- a/src/seth/libexec/seth/seth---nix-run
+++ b/src/seth/libexec/seth/seth---nix-run
@@ -9,11 +9,12 @@ set -e
 
 have() { command -v "$1" >/dev/null; }
 { have nix; } || {
-  echo >&2 "${0##*/}: error: The Nix package manager is required."
-  echo >&2 "${0##*/}: error: See https://dapp.tools for installation instructions."
-  exit 1
+	echo >&2 "${0##*/}: error: The Nix package manager is required."
+	echo >&2 "${0##*/}: error: See https://dapp.tools for installation instructions."
+	exit 1
 }
 
-expr="$1"; shift
+expr="$1"
+shift
 
 nix run "(with import $DAPPTOOLS {}; $expr)" -c "$@"
diff --git a/src/seth/libexec/seth/seth-debug b/src/seth/libexec/seth/seth-debug
--- a/src/seth/libexec/seth/seth-debug
+++ b/src/seth/libexec/seth/seth-debug
@@ -17,50 +17,57 @@ export GIT_AUTHOR_EMAIL=hevm@dapphub.com
 export GIT_COMMITTER_NAME=$GIT_AUTHOR_NAME
 export GIT_COMMITTER_EMAIL=$GIT_AUTHOR_EMAIL
 gitopts=(-q --no-verify --no-gpg-sign --allow-empty -m "dapp test")
-( cd "$state" || exit ; git init -q && git add . && git commit "${gitopts[@]}" )
+(
+	cd "$state" || exit
+	git init -q && git add . && git commit "${gitopts[@]}"
+)
 
 targetTx=$(seth tx "$1")
 
 # TODO: scary rm -rf
 tidy() {
-  [[ "$SRCDIR" ]] && rm -rf "$SRCDIR"
-  rm -rf "$state"
+	[[ "$SRCDIR" ]] && rm -rf "$SRCDIR"
+	rm -rf "$state"
 }
 trap tidy SIGINT SIGTERM
 
 if [[ -z "$SETH_NOSRC" ]]; then
-  echo >&2 "${0##*/}: info: fetching contract source from etherscan..."
-  SRCDIR=$(TMPDIR=. mktemp -d seth.debug.XXXX -p /tmp)
-  if seth bundle-source "$(<<< "$targetTx" seth --field to)" --dir "$SRCDIR" > "$SRCDIR"/standard.json ; then
-    opts=(--source "$SRCDIR"/standard.json);
-  else
-    echo >&2 "${0##*/}: warning: no source available"
-  fi
+	echo >&2 "${0##*/}: info: fetching contract source from etherscan..."
+	SRCDIR=$(TMPDIR=. mktemp -d seth.debug.XXXX -p /tmp)
+	if seth bundle-source "$(seth <<<"$targetTx" --field to)" --dir "$SRCDIR" >"$SRCDIR"/standard.json; then
+		opts=(--source "$SRCDIR"/standard.json)
+	else
+		echo >&2 "${0##*/}: warning: no source available"
+	fi
 fi
 
-index="$(<<< "$targetTx" seth --field transactionIndex)"
-block=$(seth block "$(<<< "$targetTx" seth --field blockNumber)" --full)
-txs=($(<<< "$block" seth --field transactions | seth --show-json))
-timestamp="$(<<< "$block" seth --field timestamp)"
+index="$(seth <<<"$targetTx" --field transactionIndex)"
+block=$(seth block "$(seth <<<"$targetTx" --field blockNumber)" --full)
+txs=($(seth <<<"$block" --field transactions | seth --show-json))
+timestamp="$(seth <<<"$block" --field timestamp)"
 
 j=0
 for i in "${txs[@]}"; do
-  tx=$(<<< "$i" seth --show-json)
-  hash=$(<<< "$tx" seth --field hash)
+	tx=$(seth <<<"$i" --show-json)
+	hash=$(seth <<<"$tx" --field hash)
 
-  if [[ "$1" = "$hash" ]]; then
-    echo -e >&2 "\r${0##*/}: info: transaction ($j/$index)"
-    seth run-tx "$tx" --state "$state" --debug "${opts[@]}"
-    tidy
-    break
-  else
-    [[ $SETH_VERBOSE ]] &&
-      echo -e  >&2 "\r${0##*/}: info: transaction ($j/$index)" ||
-      echo -en >&2 "\r${0##*/}: info: transaction ($j/$index)"
-    # exit code 2 means REVERT or otherwise acceptable failure
-    seth run-tx "$tx" --state "$state" --timestamp "$timestamp" > /dev/null ||
-      [[ $? == 2 ]] ||
-      (tidy; echo ""; seth --fail "${0##*/}: error: hevm error while executing tx: $hash")
-    j=$((j + 1))
-  fi
+	if [[ "$1" = "$hash" ]]; then
+		echo -e "\r${0##*/}: info: transaction ($j/$index)" >&2
+		seth run-tx "$tx" --state "$state" --debug "${opts[@]}"
+		tidy
+		break
+	else
+		[[ $SETH_VERBOSE ]] &&
+			echo -e "\r${0##*/}: info: transaction ($j/$index)" >&2 ||
+			echo -en "\r${0##*/}: info: transaction ($j/$index)" >&2
+		# exit code 2 means REVERT or otherwise acceptable failure
+		seth run-tx "$tx" --state "$state" --timestamp "$timestamp" >/dev/null ||
+			[[ $? == 2 ]] ||
+			(
+				tidy
+				echo ""
+				seth --fail "${0##*/}: error: hevm error while executing tx: $hash"
+			)
+		j=$((j + 1))
+	fi
 done
diff --git a/src/seth/libexec/seth/seth-rpc b/src/seth/libexec/seth/seth-rpc
--- a/src/seth/libexec/seth/seth-rpc
+++ b/src/seth/libexec/seth/seth-rpc
@@ -4,8 +4,8 @@ set -e
 version=$(jshon --version)
 min=20131105
 if [[ $version -lt $min ]]; then
-  echo >&2 "${0##*/}: error: jshon $version is too old (need $min or newer)"
-  exit 1
+	echo >&2 "${0##*/}: error: jshon $version is too old (need $min or newer)"
+	exit 1
 fi
 
 rpc-result() { jshon -Q -e result -j; }
@@ -15,13 +15,14 @@ request=$(seth rpc-request -- "$@")
 response=$(seth rpc-curl <<<"$request")
 
 if result=$(rpc-result <<<"$response"); then
-  seth --show-json <<<"$result"
+	seth --show-json <<<"$result"
 elif error=$(rpc-error <<<"$response"); then
-  { echo "$request"
-    SETH_KEY_WIDTH=10 seth --show-json <<<"$error" | sed 's/^/error:   /'
-  } | sed >&2 "s/^/${0##*/}: /"
-  exit 1
+	{
+		echo "$request"
+		SETH_KEY_WIDTH=10 seth --show-json <<<"$error" | sed 's/^/error:   /'
+	} | sed >&2 "s/^/${0##*/}: /"
+	exit 1
 else
-  echo >&2 "$response"
-  exit 1
+	echo >&2 "$response"
+	exit 1
 fi
